<?xml version="1.0" encoding="utf-8"?><Database Name="3328" Class="adminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.171.36;Initial Catalog=3328;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="_3328ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ticketAdmin" Member="ticketAdmins">
    <Type Name="ticketAdmin">
      <Column Name="adminid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>