#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMvcApp.DataComponent
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="3328")]
	public partial class CarInfoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCARINFO(CARINFO instance);
    partial void UpdateCARINFO(CARINFO instance);
    partial void DeleteCARINFO(CARINFO instance);
    #endregion
		
		public CarInfoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["_3328ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarInfoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarInfoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarInfoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarInfoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CARINFO> CARINFOs
		{
			get
			{
				return this.GetTable<CARINFO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARINFO")]
	public partial class CARINFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ENTRYID;
		
		private string _BRANDNAME;
		
		private string _MODEL;
		
		private string _BODYTYPE;
		
		private string _ENGINE;
		
		private int _CAPACITY;
		
		private string _FUELTYPE;
		
		private int _PRICE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnENTRYIDChanging(int value);
    partial void OnENTRYIDChanged();
    partial void OnBRANDNAMEChanging(string value);
    partial void OnBRANDNAMEChanged();
    partial void OnMODELChanging(string value);
    partial void OnMODELChanged();
    partial void OnBODYTYPEChanging(string value);
    partial void OnBODYTYPEChanged();
    partial void OnENGINEChanging(string value);
    partial void OnENGINEChanged();
    partial void OnCAPACITYChanging(int value);
    partial void OnCAPACITYChanged();
    partial void OnFUELTYPEChanging(string value);
    partial void OnFUELTYPEChanged();
    partial void OnPRICEChanging(int value);
    partial void OnPRICEChanged();
    #endregion
		
		public CARINFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENTRYID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ENTRYID
		{
			get
			{
				return this._ENTRYID;
			}
			set
			{
				if ((this._ENTRYID != value))
				{
					this.OnENTRYIDChanging(value);
					this.SendPropertyChanging();
					this._ENTRYID = value;
					this.SendPropertyChanged("ENTRYID");
					this.OnENTRYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANDNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BRANDNAME
		{
			get
			{
				return this._BRANDNAME;
			}
			set
			{
				if ((this._BRANDNAME != value))
				{
					this.OnBRANDNAMEChanging(value);
					this.SendPropertyChanging();
					this._BRANDNAME = value;
					this.SendPropertyChanged("BRANDNAME");
					this.OnBRANDNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODEL", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string MODEL
		{
			get
			{
				return this._MODEL;
			}
			set
			{
				if ((this._MODEL != value))
				{
					this.OnMODELChanging(value);
					this.SendPropertyChanging();
					this._MODEL = value;
					this.SendPropertyChanged("MODEL");
					this.OnMODELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BODYTYPE", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string BODYTYPE
		{
			get
			{
				return this._BODYTYPE;
			}
			set
			{
				if ((this._BODYTYPE != value))
				{
					this.OnBODYTYPEChanging(value);
					this.SendPropertyChanging();
					this._BODYTYPE = value;
					this.SendPropertyChanged("BODYTYPE");
					this.OnBODYTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENGINE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ENGINE
		{
			get
			{
				return this._ENGINE;
			}
			set
			{
				if ((this._ENGINE != value))
				{
					this.OnENGINEChanging(value);
					this.SendPropertyChanging();
					this._ENGINE = value;
					this.SendPropertyChanged("ENGINE");
					this.OnENGINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int NOT NULL")]
		public int CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this.OnCAPACITYChanging(value);
					this.SendPropertyChanging();
					this._CAPACITY = value;
					this.SendPropertyChanged("CAPACITY");
					this.OnCAPACITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FUELTYPE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FUELTYPE
		{
			get
			{
				return this._FUELTYPE;
			}
			set
			{
				if ((this._FUELTYPE != value))
				{
					this.OnFUELTYPEChanging(value);
					this.SendPropertyChanging();
					this._FUELTYPE = value;
					this.SendPropertyChanged("FUELTYPE");
					this.OnFUELTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Int NOT NULL")]
		public int PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
