//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTSDB
    {
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string IMAGE { get; set; }
        public int PRICE { get; set; }
        public int QUANTITY { get; set; }
    }
}
